a = input('enter subjects of student a  ')
std_a = set(a.split())
b = input('enter subjects of student b  ')
std_b = set(b.split())
print(std_a)
print(std_b)
print('subjects common to both students: ' , std_a & std_b)
print('subjects only a has: ', std_a - std_b)
print('subjects only student b has: ', std_b - std_a)